swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8096'
basePath: /mock/vesta/v1
tags:
  - name: payment-controller
    description: Payment Controller
  - name: session-controller
    description: Session Controller
  - name: tax-controller
    description: Tax Controller
paths:
  /chargeOrderAuthorizeWithToken:
    post:
      tags:
        - payment-controller
      summary: chargeOrderPrepareWithToken
      operationId: chargeOrderPrepareWithTokenUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: chargeOrderAuthorizeWithTokenRequest
          description: chargeOrderAuthorizeWithTokenRequest
          required: true
          schema:
            $ref: '#/definitions/ChargeOrderAuthorizeWithTokenRequest'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /chargeOrderConfirmWithAnonymous:
    post:
      tags:
        - payment-controller
      summary: anonymousProcessOrder
      operationId: anonymousProcessOrderUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: chargeOrderConfirmWithAnonymousRequest
          description: chargeOrderConfirmWithAnonymousRequest
          required: true
          schema:
            $ref: '#/definitions/ChargeOrderConfirmWithAnonymousRequest'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /orderTaxAndFeeDetails:
    post:
      tags:
        - tax-controller
      summary: getTaxes
      operationId: getTaxesUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: orderTaxAndFeeDetailsRequest
          description: orderTaxAndFeeDetailsRequest
          required: true
          schema:
            $ref: '#/definitions/OrderTaxAndFeeDetailsRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /sessionCreate:
    post:
      tags:
        - session-controller
      summary: createPaymentSession
      operationId: createPaymentSessionUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: sessionCreateRequest
          description: sessionCreateRequest
          required: true
          schema:
            $ref: '#/definitions/SessionCreateRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ChargeOrderAuthorizeWithTokenRequest:
    type: object
    properties:
      AccountNumber:
        type: string
      ChargeAccountNumberToken:
        type: string
      MDN:
        type: string
      OrderType:
        type: integer
        format: int32
      OriginatingIPAddress:
        type: string
      PDAddressLine1:
        type: string
      PDCity:
        type: string
      PDCountryCode:
        type: string
      PDFirstName:
        type: string
      PDLastName:
        type: string
      PDPostalCode:
        type: string
      PDRegion:
        type: string
      PackedData:
        type: string
      SessionKey:
        type: string
      TaxDetail:
        type: array
        items:
          $ref: '#/definitions/TaxDetail'
      TotalChargeAmount:
        type: number
        format: double
      TotalTaxAmount:
        type: number
        format: double
      TransactionID:
        type: string
      pdAddressLine2:
        type: string
    title: ChargeOrderAuthorizeWithTokenRequest
  ChargeOrderConfirmWithAnonymousRequest:
    type: object
    properties:
      OrderID:
        type: string
      PlatformIntegration:
        type: string
      SessionKey:
        type: string
    title: ChargeOrderConfirmWithAnonymousRequest
  OrderTaxAndFeeDetailsRequest:
    type: object
    properties:
      Amount:
        type: number
        format: double
      MDN:
        type: string
      OriginatingIPAddress:
        type: string
      PDCountryCode:
        type: string
      PostalCode:
        type: string
      SessionKey:
        type: string
    title: OrderTaxAndFeeDetailsRequest
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  SessionCreateRequest:
    type: object
    properties:
      ChannelCode:
        type: integer
        format: int32
      PartnerChannelCode:
        type: string
      PartnerChannelDescriptor:
        type: string
      PartnerCode:
        type: integer
        format: int32
      PartnerRetailerID:
        type: string
      PartnerSystemTrackingID:
        type: string
      PartnerUserID:
        type: string
      VendorID:
        type: string
      VendorPassword:
        type: string
    title: SessionCreateRequest
  TaxDetail:
    type: object
    properties:
      Amount:
        type: number
        format: double
      Description:
        type: string
      TaxTypeCD:
        type: integer
        format: int32
    title: TaxDetail
