swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8095'
basePath: /subscription/v1
tags:
  - name: subscription-controller
    description: Subscription Controller
paths:
  /subscription/balance/card:
    post:
      tags:
        - subscription-controller
      summary: creditCardTopUp
      operationId: creditCardTopUpUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: creditCardTopUpRequest
          description: creditCardTopUpRequest
          required: true
          schema:
            $ref: '#/definitions/CreditCardTopUpRequest'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /subscription/balance/voucher:
    post:
      tags:
        - subscription-controller
      summary: refill
      operationId: refillUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: reCaptchaToken
          in: query
          description: reCaptchaToken
          required: true
          type: string
        - in: body
          name: topupRequest
          description: topupRequest
          required: true
          schema:
            $ref: '#/definitions/TopupRequest'
        - name: version
          in: query
          description: version
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TopupResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/subscription/{phoneNumber}/balance':
    get:
      tags:
        - subscription-controller
      summary: getSubscriptionBalance
      operationId: getSubscriptionBalanceUsingGET
      produces:
        - '*/*'
      parameters:
        - name: phoneNumber
          in: path
          description: phoneNumber
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  BillingAddress:
    type: object
    properties:
      addressLine1:
        type: string
      addressLine2:
        type: string
      city:
        type: string
      country:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      postalCode:
        type: string
      province:
        type: string
    title: BillingAddress
  CreditCardTopUpRequest:
    type: object
    properties:
      amount:
        type: number
        format: double
      billingAddress:
        $ref: '#/definitions/BillingAddress'
      packedData:
        type: string
      phoneNumber:
        type: string
      tax:
        type: number
        format: double
      token:
        type: string
    title: CreditCardTopUpRequest
  TopupRequest:
    type: object
    properties:
      phone:
        type: string
      vouchers:
        type: array
        items:
          $ref: '#/definitions/Voucher'
    title: TopupRequest
  TopupResponse:
    type: object
    properties:
      invalidVouchers:
        type: array
        items:
          $ref: '#/definitions/VoucherResponse'
      totalSum:
        type: number
    title: TopupResponse
  Voucher:
    type: object
    properties:
      voucherPin:
        type: string
    title: Voucher
  VoucherResponse:
    type: object
    properties:
      responseCode:
        type: integer
        format: int32
      voucherPin:
        type: string
    title: VoucherResponse
