swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8185'
basePath: /tax/v1
tags:
  - name: tax-controller
    description: Tax Controller
paths:
  /tax:
    post:
      tags:
        - tax-controller
      summary: getTaxes
      operationId: getTaxesUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: taxRequest
          description: taxRequest
          required: true
          schema:
            $ref: '#/definitions/TaxRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TaxResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  TaxDetailInfo:
    type: object
    properties:
      amount:
        type: number
        format: double
      description:
        type: string
      taxTypeCD:
        type: integer
        format: int32
    title: TaxDetailInfo
  TaxRequest:
    type: object
    properties:
      amount:
        type: number
        format: double
      countryCode:
        type: string
      ipAddress:
        type: string
      mdn:
        type: string
      postalCode:
        type: string
    title: TaxRequest
  TaxResponse:
    type: object
    properties:
      sessionKey:
        type: string
      taxDetail:
        type: array
        items:
          $ref: '#/definitions/TaxDetailInfo'
      totalAmount:
        type: number
        format: double
      totalTax:
        type: number
        format: double
    title: TaxResponse
